version: '3.8'

services:
  mysqldb:
    image: mysql/mysql-server:5.6.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: InciDatabase
      MYSQL_USER: 'InciUser'
      MYSQL_PASSWORD: 'password'
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
  server:
    restart: always
    build:
      context: ./server
    image: server
    depends_on:
      - mysqldb
    ports:
      - 8080:8080

volumes:
  db-data:
